spring:
  application:
    name: PLAYER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/cybersport
    username: root
    password: 915327
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    database: 1
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8094

logging:
  level:
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG

eureka:
  client:
    instance:
      hostname: localhost
    service-url:
      defaultZone: http://localhost:8761/eureka