spring:
  application:
    name: DISCOVERY
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8761

eureka:
  client:
    instance:
      hostname: localhost
    service-url:
      defaultZone: http://localhost:8761/eureka